# Generated by Django 4.0 on 2022-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
