# Generated by Django 4.0 on 2022-02-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ST', 'student'), ('SU', 'supervisor'), ('HOD', 'HeadOfDepartment'), ('DA', 'DepartmentAdmin'), ('A', 'admin')], max_length=3, null=True),
        ),
    ]
