# Generated by Django 4.0 on 2022-02-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dprtadmin',
            options={'verbose_name_plural': 'DprtAdmin'},
        ),
        migrations.AlterModelOptions(
            name='hod',
            options={'verbose_name_plural': 'HOD'},
        ),
    ]
