# Generated by Django 4.0 on 2022-02-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_dprtadmin_options_alter_hod_options'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.proposal'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.supervisor'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pen', 'pending'), ('ahod', 'accepted by HOD'), ('rsup', 'rejected by supervisor'), ('rhod', 'rejected by HOD'), ('asup', 'accepted by supervisor'), ('aadm', 'accepted by admin'), ('radm', 'rejected by admin')], default='pen', max_length=4),
        ),
    ]
