# Generated by Django 4.0 on 2022-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('asup', 'accepted by supervisor'), ('pen', 'pending'), ('aadm', 'accepted by admin'), ('rsup', 'rejected by supervisor'), ('ahod', 'accepted by HOD'), ('radm', 'rejected by admin'), ('rhod', 'rejected by HOD')], default='pen', max_length=4),
        ),
    ]
