# Generated by Django 4.0 on 2022-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('ahod', 'accepted by HOD'), ('asup', 'accepted by supervisor'), ('pen', 'pending'), ('aadm', 'accepted by admin'), ('rhod', 'rejected by HOD'), ('rsup', 'rejected by supervisor'), ('radm', 'rejected by admin')], default='pen', max_length=4),
        ),
    ]
