# Generated by Django 4.0 on 2022-02-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('aadm', 'accepted by admin'), ('rhod', 'rejected by HOD'), ('radm', 'rejected by admin'), ('ahod', 'accepted by HOD'), ('asup', 'accepted by supervisor'), ('rsup', 'rejected by supervisor'), ('pen', 'pending')], default='pen', max_length=4),
        ),
    ]
