# Generated by Django 4.0 on 2022-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('document', '0003_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('radm', 'rejected by admin'), ('asup', 'accepted by supervisor'), ('rsup', 'rejected by supervisor'), ('rhod', 'rejected by HOD'), ('ahod', 'accepted by HOD'), ('pen', 'pending'), ('aadm', 'accepted by admin')], default='pen', max_length=4),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='student',
        ),
        migrations.AddField(
            model_name='proposal',
            name='student',
            field=models.ManyToManyField(to='account.Student'),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='proposal',
            name='supervisor',
            field=models.ManyToManyField(to='account.Supervisor'),
        ),
    ]
