# Generated by Django 4.0 on 2022-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_proposal_status_remove_proposal_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('rhod', 'rejected by HOD'), ('pen', 'pending'), ('radm', 'rejected by admin'), ('asup', 'accepted by supervisor'), ('rsup', 'rejected by supervisor'), ('ahod', 'accepted by HOD'), ('aadm', 'accepted by admin')], default='pen', max_length=4),
        ),
    ]
